### ISSUE TITLE
how to stop writing timestamp in `routes.js` file?

### ISSUE THREAD

**Issue by nov** [railsware/js-routes#324] opened 2024-12-03 04:37 UTC
everytime rails middleware auto generates the file, timestamp is updated, and cause unnecessary diff in git history.
I want to disable it not to cause unnecessary conflicts...

**Comment by bogdan** [comment] 2024-12-03 11:05
I believe unnecessary diff in git history starts from `routes.js` file committed to the repository. What is the reason you are doing that?

This is a bad idea anyway as it will cause merge conflicts even without timestamp.

**Comment by nov** [comment] 2024-12-03 13:40
We have no problem without timestamp.
Plus, we're reviewing the diff when new endpoint get disclosed in JS

**Comment by bogdan** [comment] 2024-12-03 16:16
The problem is that middleware updates `routes.js` on the first launch even if it `routes.rb` didn't change. 
After this it remembers update timestamp, but first run - it has no idea how long ago `routes.js` was updated.

Let me think if we can solve that.

**Comment by nov** [comment] 2024-12-03 22:52
I see.
If there are some configuration option not to output timestamp, it would be fine enough for us.

**Closed** 2024-12-04 08:59 UTC

**Comment by bogdan** [comment] 2024-12-04 18:14
In the end I've got too many complains about timestamp from people who are actually comiting `routes.js` into repo for variety of reasons.

While the options to customize a banner comment on top of the generated file makes a lot of sense and was on my radar for a long time, I decided to replace timestamp with the digest. 

Released 2.3.3.

@nov do you fill like this default banner makes sense for you?

**Comment by nov** [comment] 2024-12-04 20:08
Now I'm already using custom banner option, so not having timestamp nor digest.
But yes, that new default seems better.
