### ISSUE TITLE
module_type: nil causes "NIL is not supported by runtime"

### ISSUE THREAD

**Issue by khiemb** [railsware/js-routes#297] opened 2022-02-15 22:08 UTC
I'm experiencing this same error as issue #292 , with version 2.2.2

here's the stack trace

```
routes.js.erb:475 Uncaught Error: NIL is not supported by runtime
    at UtilsClass.ensure_module_supported (routes.js.erb:475:1)
    at UtilsClass.define_module (routes.js.erb:479:1)
    at routes.js.erb:1397:1
    at Module.<anonymous> (routes.js.erb:1399:1)
    at Module../app/javascript/routes.js.erb (routes.js.erb:1401:1)
    at __webpack_require__ (bootstrap:79:1)
    at Module../app/javascript/packs/application.js (application.js:1:1)
    at __webpack_require__ (bootstrap:79:1)
    at Object.1 (.*$:292:1)
    at __webpack_require__ (bootstrap:79:1)
    
   ```

**Comment by bogdan** [comment] 2022-02-16 14:32
What is your configuration?

**Comment by khiemb** [comment] 2022-02-16 19:53
i followed the 2.0 upgrade doc, so this is 

config/initializers/js_routes.rb

```
JsRoutes.setup do |config|
  config.module_type = nil
  config.namespace = "Routes"
end
```

**Comment by bogdan** [comment] 2022-02-17 16:03
I can't reproduce it locally because JS environments are too diverse. 

For the sake of debugging can you change the following method locally inside your copy of `js-routes` gem to:

``` javascript
            isSupported() {
               console.log(Root);
               console.log(Namespace);
               console.log(!!Root);
               return true;
            },
```

https://github.com/railsware/js-routes/blob/dba9abee8e1df91dc29bece2aac2b0eab9b404ee/lib/routes.js#L77

And then restart the project and tell me if it fixes your issue and what is the output in console?

**Comment by khiemb** [comment] 2022-02-17 18:52
I made the changes and this is the console output

```

﻿
routes.js.erb:77 undefined
routes.js.erb:78 Uncaught ReferenceError: Namespace is not defined
    at Object.isSupported (routes.js.erb:78:1)
    at UtilsClass.is_module_supported (routes.js.erb:476:1)
    at UtilsClass.ensure_module_supported (routes.js.erb:479:1)
    at UtilsClass.define_module (routes.js.erb:484:1)
    at routes.js.erb:1402:1
    at Module.<anonymous> (routes.js.erb:1404:1)
    at Module../app/javascript/routes.js.erb (routes.js.erb:1406:1)
    at __webpack_require__ (bootstrap:84:1)
    at Module../app/javascript/packs/application.js (application.js:1:1)
    at __webpack_require__ (bootstrap:84:1)
```

**Comment by bogdan** [comment] 2022-02-18 15:09
I tried to fix an issue. Can you try the gem from current master if it solves the problem?

**Comment by khiemb** [comment] 2022-02-21 22:08
```
Uncaught TypeError: Cannot read properties of undefined (reading 'Routes')
    at Module.<anonymous> (0-c0a5c58e421ed5570b29.chunk.js:2025:74)
    at Module../app/javascript/routes.js.erb (0-c0a5c58e421ed5570b29.chunk.js:2026:30)
    at __webpack_require__ (runtime~application-aa001ceb574a6f67800d.js:80:30)
    at Module../app/javascript/packs/application.js (application-96c4f6da898f33e3ba24.chunk.js:170:72)
    at __webpack_require__ (runtime~application-aa001ceb574a6f67800d.js:80:30)
    at Object.1 (application-96c4f6da898f33e3ba24.chunk.js:2815:18)
    at __webpack_require__ (runtime~application-aa001ceb574a6f67800d.js:80:30)
    at checkDeferredModules (runtime~application-aa001ceb574a6f67800d.js:46:23)
    at Array.webpackJsonpCallback (runtime~application-aa001ceb574a6f67800d.js:33:19)
    at application-96c4f6da898f33e3ba24.chunk.js:1:57
    ```
    
    I tried the gem from current master, and getting this error in `routes.js.erb`
    
    ```
    <%= Js.Routes.generate %>
    export default this.Routes
    ```
    
    My `js_routes.rb` file config is the same

**Comment by bogdan** [comment] 2022-02-23 11:56
See, there is a kind of problem within webpacker environment: top level `this` is equal to `undefined`. 
The problem is that you need to use one os the following depending on the JS environment: `window`, `this` or `global`.
You need to use this code snippet if you really need that: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis#search_for_the_global_across_environments


Overall I do not recommend a configuration like this. It is not environment agnostic.

You should try instead:

``` ruby
JsRoutes.setup do |config|
  config.module_type = nil
end
```

``` javascript
const Routes = <%= JsRoutes.generate %>
export Routes;
```

**Comment by bogdan** [comment] 2022-03-21 15:36
No followup, closing. Feel free to reopen.

**Closed by bogdan** 2022-03-21 15:36 UTC
