### ISSUE TITLE
Expose Utils to add custom routes

### ISSUE THREAD

**Issue by hakunin** [railsware/js-routes#194] opened 2016-06-15 13:00 UTC
Hi,
this is very useful and I would like to also use it to create routes for client side that uses pushState.

Have you thought about exposing `Utils`?

**Comment by bogdan** [comment] 2016-06-15 14:28
There always need to be a part of JS routes that is private. We can not maintain all the methods we have with a consistent API forever.
If you need a particular thing from `Utils`, tell us which one and describe the use case very clearly.

**Comment by hakunin** [comment] 2016-06-16 04:39
I wanted to add some client side routes, that don't exist in the backend, but are managed as client side pushState routes.

```
    resources :boards do
      member do        
        # this allows us to export the virtual routes to client
        get '*client_url', to: :show
      end
    end
```

You can see that `*client_url` route, its a catch-all route. Now I need to add the rest of the client routes somehow.

Makes sense?

**Comment by bogdan** [comment] 2016-06-16 05:57
Not yet, so which method from utils do you need and how would you use it?

**Comment by hakunin** [comment] 2016-06-16 06:03
I was going to use the Utils.route that constructs these urls:

```
var app_search_path: Utils.route([], ["format"], [2,[7,"/",false],[2,[6,"app",false],[2,[7,"/",false],[2,[6,"search",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]], {}),
```

But somehow when I gsubbed the js code to expose `Utils`, I couldn't get it to work.

**Comment by bogdan** [comment] 2016-06-16 07:02
Wow that would be pretty inconvenient to use. I don't think this is usable.
The right API would be:

``` js
var app_search_path = Utils.route("/app/search(.:format)")
```

But it would be very hard to implement. JS part of the gem can not parse route spec like rails does.

**Comment by hakunin** [comment] 2016-06-16 08:01
Yeah, that would be way nicer.
Maybe the routes could be specified in the server side code to avoid any JS parsing.

Anyway, as I had to specify most of the routes manually and couldn't use Utils I ended up not using this gem.

**Comment by bogdan** [comment] 2016-06-16 08:42
If you are fine with route defined on backend, why you can define the following on backend:

```
get "/app/search", as: :app_search
```

**Comment by hakunin** [comment] 2016-06-16 08:46
Yeah, I tried that approach, but it didn't seem super clean to do it in the router. 
Ended up with a couple of catch all routes.

**Comment by bogdan** [comment] 2016-06-16 08:48
Why not? You may put those to a separated scope:

```
  scope "/app", as: :app do
    get "/search" => "home#index"
  end
```

**Comment by hakunin** [comment] 2016-06-16 08:59
I wanted to keep it dry and not hand write each route. We'll see how it goes and maybe I'll give it another shot. If you want to close this, please do.

**Comment by bogdan** [comment] 2016-06-16 09:13
I don't see how you would "not hand write each route". I am ok keeping this open... as it has a value. We should continue discussing.

**Comment by bogdanRada** [comment] 2016-06-23 07:41
This would be really helpful if the Utils could be exposed and there could be a nicer API. Currently i had to copy the routes.js locally and modify it a bit to be able to add custom routes 

E.g.  for this URL 
```ruby 
/products/bags/:id/confirm-action/:type(.:format) 
``` 

I had to do this: 

```js
Utils.route(["id","type"], ["format"], [2,[2,[2,[7,"/",false],[6,"products",false]],[7,"/",false]],[2,[6,"bags",false],[2,[7,"/",false],[2,[3,"id",false],[2,[7,"/",false],[2,[6,"confirm-action",false],[2,[7,"/",false],[2,[3,"type",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]], arguments)
```

which is really ugly and very hard to understand.  

Is there any change this could be generated in a easier way?

**Comment by le0pard** [comment] 2016-06-23 07:43
@bogdanRada why this route not present in rails routes?

**Comment by bogdanRada** [comment] 2016-06-23 07:49
I use this In Rails routes:
```ruby
MyGem::Engine.routes.draw do
  resources :bags, as: 'product', except: [:destroy] do |product = 'bags'|
    member do
       get 'confirm-action/:type' ,:as => :confirm_action, :action => :confirm_action
    end
  end 
end
```

And then i mount it like this:
```ruby
Rails.application.routes.draw do
    mount MyGem::Engine       => '/products'
end
```

But i need to generate same routes on JS side also. That;s why i am using the Utils module in Javascript

**Comment by bogdan** [comment] 2016-06-23 15:11
What is the output of `rake routes | grep /products` ? Do you have the mounted routes there?

**Comment by bogdanRada** [comment] 2016-06-23 16:09
The engines routes look like this:
```bash
Routes for MyGem::Engine:
confirm_action_product GET   /bags/:id/confirm-action/:type(.:format) my_gem/bags#confirm_action
         product_index GET   /bags(.:format)                          my_gem/bags#index
                       POST  /bags(.:format)                          my_gem/bags#create
           new_product GET   /bags/new(.:format)                      my_gem/bags#new
          edit_product GET   /bags/:id/edit(.:format)                 my_gem/bags#edit
               product GET   /bags/:id(.:format)                      my_gem/bags#show
                       PATCH /bags/:id(.:format)                      my_gem/bags#update
                       PUT   /bags/:id(.:format)                      my_gem/bags#update

```

And main application has this:

```bash
                  Prefix Verb     URI Pattern        Controller#Action
                  core             /                  Core::Engine
                  my_gem          /products             MyGem::Engine
```

**Comment by le0pard** [comment] 2016-06-23 16:12
@bogdanRada can you change code `mount MyGem::Engine       => '/products'` to this `mount MyGem::Engine       => '/products', as: :products` and check js routes again (clear `tmp` cache)? Looks like you don't have named route for engine.

**Comment by bogdanRada** [comment] 2016-06-23 16:15
I know though where the issue is https://github.com/railsware/js-routes/blob/master/lib/js_routes.rb#L152

And there is a solution . you are only iterating over Rails.application.routes and not going recursive over them. 

You can see here though how you can do that https://github.com/inossidabile/wash_out/blob/master/lib/wash_out/router.rb#L7  

Of course you don't need to check the action of a route or the controller name, But this might help you a bit.

**Comment by bogdanRada** [comment] 2016-06-23 16:20
I tried your suggestion, but as you can see, the routes from the engine are the same

```bash
Routes for MyGem::Engine:
confirm_action_product GET   /bags/:id/confirm-action/:type(.:format) my_gem/bags#confirm_action
         product_index GET   /bags(.:format)                          my_gem/bags#index
                       POST  /bags(.:format)                          my_gem/bags#create
           new_product GET   /bags/new(.:format)                      my_gem/bags#new
          edit_product GET   /bags/:id/edit(.:format)                 my_gem/bags#edit
               product GET   /bags/:id(.:format)                      my_gem/bags#show
                       PATCH /bags/:id(.:format)                      my_gem/bags#update
                       PUT   /bags/:id(.:format)                      my_gem/bags#update
```
and this for main application

```bash

                     Prefix Verb     URI Pattern              Controller#Action
                     core               /                   Core::Engine
                    products          /products              MyGem::Engine
```

So that doesn't help much

**Comment by le0pard** [comment] 2016-06-23 16:22
@bogdanRada so routes in js doesn't contain additional routes (I mean js file, not `rake routes` command)?

**Comment by bogdanRada** [comment] 2016-06-23 16:22
yes

**Comment by le0pard** [comment] 2016-06-23 16:24
Ok, looks like bug, because this code should work: https://github.com/railsware/js-routes/blob/master/lib/js_routes.rb#L155-L158

**Comment by bogdanRada** [comment] 2016-06-23 16:31
Sorry, now seems to work :) I wasn't using the correct expression when searching in the file. Didn't know about the :as option. Thank you very much.

**Comment by bogdanRada** [comment] 2016-06-23 16:34
But the code shouldn't use the mounted path of the engine? I mean you can mount multiple engines at /products, but you can't name them the same.

**Comment by le0pard** [comment] 2016-06-23 16:36
Code using name of routes, because this name need to make name of functions which will return route.

**Comment by bogdanRada** [comment] 2016-06-23 16:38
But that approach is wrong. You should be using the mounted_path, becasue that path is used when accessing the URL in browser

and you can't use same :as option for two engines, becasue then you get this error
ArgumentError: Invalid route name, already in use: 'products' 
You may have defined two routes with the same name using the `:as` option, or you may be overriding a route already defined by a resource with the same naming. For the latter, you can restrict the routes created with `resources` as explained here: 
http://guides.rubyonrails.org/routing.html#restricting-the-routes-created

**Comment by le0pard** [comment] 2016-06-23 16:41
Names of routes need to make possible change only mounted path, but not name of using route. Example:

```
mount MyGem::Engine => '/products', as: :products
mount MySecondGem::Engine => '/products', as: :second_products
```

If I need change path for `MySecondGem::Engine`, I just change it, but not the name inside backend code (Ruby) and frontend code (JS), only:

```
mount MyGem::Engine => '/products', as: :products
mount MySecondGem::Engine => '/changed_path', as: :second_products
```

So I don't see this bad, because it works as rails route helpers in the same way.

**Comment by bogdanRada** [comment] 2016-06-23 16:46
You don't understand. Since both are mounted at "/products"  all the routes from these engines will be using /products as a prefix,  not the :as option name. 

Having two products that you want to sell, would be more SEO friendly to use /product/apples and /products/bags then changing them to some ugly routes like /products/apples and /my_products/bags

That really defeats the purpose of SEO. 

So sometimes you just can't mount engines at different paths. 

And i really suggest to re-consider my proposal to use the mounted paths of the engines

**Comment by le0pard** [comment] 2016-06-23 16:50
I understand, but don't understand problem with naming (not mounted path). Use different naming for mounted engine, what the problem? At least it will be clear from what engine comes this route.

**Comment by bogdanRada** [comment] 2016-06-23 16:55
It is a very big problem, because i don't want to put different prefixes for URLS that should use same prefix, and for SEO. 
if you don't know how to get the mounted paths you can see here: https://github.com/bogdanRada/washout_builder/blob/master/app/controllers/washout_builder/washout_builder_controller.rb#L88 

Very easy to do.

**Comment by bogdanRada** [comment] 2016-06-23 16:57
Yes, i could use different naming, expect for really big applications, where i can't go and start to update all routes.

**Comment by le0pard** [comment] 2016-06-23 17:04
> It is a very big problem, because i don't want to put different prefixes for URLS that should use same prefix, and for SEO. 

So it is not big problem for everyone, only for you. 

First of all, js-routes should work as rails route helpers. If rails route helpers (I mean `*_path` and `*_url` helpers) works based `mounted_path`, we will fix this. But as I can see, we works as expected:

```
mount Sidekiq::Web => '/sidekiq', :as => :sidekiq
```

and I get

```
2.3.1 :002 > app.sidekiq_path
 => "/sidekiq"
```

Possible problem if we will working for mounted path, like this case:

```
mount Sidekiq::Web => '/sidekiq'
get "/products" => "products#index", as: :sidekiq
```

In this case we have conflict with mounted engine path and named route, but in real app, mounted engine no name of path, so not helper functions for it. We works in the same way.

**Comment by bogdanRada** [comment] 2016-06-23 17:10
You're wrong. Let me explain:

if you have this:
```ruby
mount MyGem::Engine => "/products", as: :my_gem
```

then will work like this:
```ruby
Loading development environment (Rails 4.2.4)
[1] pry(main)> app.my_gem_path
=> "/products"

```

but if you have this:
```ruby
mount MyGem::Engine => "/products", as: :my_gem2
```

then will work like this:
```ruby
Loading development environment (Rails 4.2.4)
[1] pry(main)> app.my_gem2_path
=> "/products"

```


See now? changing only the :as option , changes also how the path helpers are used.

**Comment by le0pard** [comment] 2016-06-23 17:11
@bogdanRada And where exactly I am wrong?

**Comment by bogdanRada** [comment] 2016-06-23 17:14
i don't think this discussion is going anywhere. You are failing to see that for large applications, that don't have the :as option defined for their engines, adding them would require a lot of work,  when this could be solved though internally by this gem and not doing hacks in application just to make the gem work .

**Comment by le0pard** [comment] 2016-06-23 17:21
> You are failing to see that for large applications, that don't have the :as option defined for their engines, adding them would require a lot of work, when this could be solved though internally by this gem and not doing hacks in application just to make the gem work .

I think you making a snap judgment, because you really don't know why type of applications I have. If I need route helpers for mounted engines - I add names for its. js-routes just works in the same pattern, but on frontend. If engineer no need route helpers (in Ruby and JS) long time, and right now understand what he/she need this helpers right now - it is сertainly not a problem of the library. Because js-routes should provide routes helpers on frontend in the same way as Rails helpers on backend.

**Comment by bogdanRada** [comment] 2016-06-23 17:23
> . Because js-routes should provide routes helpers on frontend in the same way as Rails helpers on backend.

That's the thing, it only works if you add the :as option, But Rails works even if you don't. So this is not an exact match. You say this gem should be an exact match of these routes. Well it is NOT.

**Comment by le0pard** [comment] 2016-06-23 17:28
@bogdanRada Now it is clear. So if rails generate for `mount MyGem::Engine => "/products"` some helper route (based on mounted path), we should extract this. Better create separate issue for this.

**Comment by bogdanRada** [comment] 2016-06-23 18:57
I created the separate issue. Thank you very much for being so patient. I admit there was some communication issues , probably because of me. I wasn't sure exactly how to explain it. Thank you very much though for the help and for responding so quickly :) I really appreciate all the help .

**Comment by bogdan** [comment] 2016-07-04 14:29
@le0pard this discussion was polluted a lot with unreleated items. Can you update the description of the initial ticket to match the current requirements?

**Comment by le0pard** [comment] 2016-07-04 14:35
I think we can just close it, because if you need route, which should catch any path by prefix, it can be done very simple:

```
function superPuperRoute(path) {
  return "/prefix/" + path;
}
```

**Closed** 2016-07-12 09:14 UTC
