### ISSUE TITLE
Optional route segment causes left side of url to be lost

### ISSUE THREAD

**Issue by mttdffy** [railsware/js-routes#188] opened 2016-04-14 18:52 UTC
We have an application with a locale constraint applied to the routes. For the administration of the site, the url looks something like this:

```
/admin/(:locale)/dashboard
```

We've noticed that when the locale is not provided, js-routes returns `/dashboard`, instead of the expected `/admin/dashboard`. I've determined that the problem comes from the serialization of the route specs, where the `/admin/(:locale)` segments are a  `GROUP` node which makes all segments of the group optional in `Utils#visit` in `routes.js`, although this should not be the case with the `/admin/` segment.

**Comment by le0pard** [comment] 2016-04-14 18:53
I think this is dup of https://github.com/railsware/js-routes/issues/86

**Comment by mttdffy** [comment] 2016-04-14 18:56
Apologizes. I believe you are correct. Thanks for the quick reply.

**Comment by le0pard** [comment] 2016-04-14 18:57
@mttdffy you can try to make PR, some possible solutions you can read in comments

**Comment by bogdan** [comment] 2016-04-14 19:16
I don't see this as a duplicate of #86. @le0pard are you sure?

**Comment by le0pard** [comment] 2016-04-14 19:18
@bogdan optional part in url - looks the same.

**Comment by bogdan** [comment] 2016-04-14 19:54
I don't think so, #86 is about a parameter treated as an option or as an serialised object.

@mttdffy I tried to make a test for your case and passed:

``` diff
diff --git a/spec/js_routes/rails_routes_compatibility_spec.rb b/spec/js_routes/rails_routes_compatibility_spec.rb
index 71e27e3..4821ca6 100644
--- a/spec/js_routes/rails_routes_compatibility_spec.rb
+++ b/spec/js_routes/rails_routes_compatibility_spec.rb
@@ -316,4 +316,8 @@ describe JsRoutes, "compatibility with Rails"  do
   end


+  it "works" do
+    expect(evaljs("Routes.admin_dashboard_path()")).to eq(routes.admin_dashboard_path)
+  end
+
 end
diff --git a/spec/spec_helper.rb b/spec/spec_helper.rb
index 6568191..49f2713 100644
--- a/spec/spec_helper.rb
+++ b/spec/spec_helper.rb
@@ -121,6 +121,8 @@ def draw_routes

     get '/' => 'sso#login', host: 'sso.example.com', as: :sso

+    get '/admin/(:locale)/dashboard' => "admin#index", as: :admin_dashboard
+
     resources :portals, :port => 8080

     namespace :api, format: true, defaults: {format: 'json'} do
```

Is it right?

**Comment by le0pard** [comment] 2016-04-14 20:12
@bogdan sorry, I was wrong.

**Comment by bogdan** [comment] 2016-04-29 08:52
@mttdffy any feedback here?

**Closed** 2016-05-04 16:08 UTC
